name: Multi platform build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install required libraries
        run: |
          sudo apt update
          sudo apt install -y make pkgconf libsdl2-dev libasound2-plugins libjack-dev python3-pillow

      - name: Build X64
        working-directory: projects
        run: make PLATFORM=X64

      - name: Package build
        working-directory: projects
        run: |
          curl -L -o lgpt-resources.zip https://github.com/djdiskmachine/lgpt-resources/archive/refs/tags/1.1.zip
          unzip lgpt-resources.zip
          mv lgpt-resources-1.1/*/ ./resources/packaging
          rm -rf lgpt-resources*
          ./resources/packaging/lgpt_package.sh

      - name: Extract Git tag name
        id: extract_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - uses: pyTooling/Actions/releaser@r0
        with:
          tag: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
          files: projects/*.zip

  build-psp:
    runs-on: ubuntu-latest
    env:
      PSPDEV: ${{ github.workspace }}/pspdev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install required libraries
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake pkgconf libusb-0.1-4 libgpgme11 libarchive-tools fakeroot python3-pillow

      - name: Set up PSP dev kit
        run: |
          echo "$PSPDEV/bin" >> $GITHUB_PATH
          git clone https://github.com/djdiskmachine/pspdev

      - name: Build PSP
        working-directory: projects
        run: make PLATFORM=PSP

      - name: Package build
        working-directory: projects
        run: |
          curl -L -o lgpt-resources.zip https://github.com/djdiskmachine/lgpt-resources/archive/refs/tags/1.1.zip
          unzip lgpt-resources.zip
          mv lgpt-resources-1.1/*/ ./resources/packaging
          rm -rf lgpt-resources*
          ./resources/packaging/lgpt_package.sh

      - name: Extract Git tag name
        id: extract_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - uses: pyTooling/Actions/releaser@r0
        with:
          tag: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
          files: projects/*.zip
